// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: ax.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AX_GetTask_FullMethodName                = "/ax.v1alpha1.AX/GetTask"
	AX_ListTasks_FullMethodName              = "/ax.v1alpha1.AX/ListTasks"
	AX_CreateTask_FullMethodName             = "/ax.v1alpha1.AX/CreateTask"
	AX_DeleteTask_FullMethodName             = "/ax.v1alpha1.AX/DeleteTask"
	AX_SuspendTask_FullMethodName            = "/ax.v1alpha1.AX/SuspendTask"
	AX_ResumeTask_FullMethodName             = "/ax.v1alpha1.AX/ResumeTask"
	AX_WatchTask_FullMethodName              = "/ax.v1alpha1.AX/WatchTask"
	AX_CreateTaskGroup_FullMethodName        = "/ax.v1alpha1.AX/CreateTaskGroup"
	AX_GetTaskGroup_FullMethodName           = "/ax.v1alpha1.AX/GetTaskGroup"
	AX_ListTaskGroups_FullMethodName         = "/ax.v1alpha1.AX/ListTaskGroups"
	AX_UpdateTaskGroup_FullMethodName        = "/ax.v1alpha1.AX/UpdateTaskGroup"
	AX_DeleteTaskGroup_FullMethodName        = "/ax.v1alpha1.AX/DeleteTaskGroup"
	AX_PrepareRuntime_FullMethodName         = "/ax.v1alpha1.AX/PrepareRuntime"
	AX_GetPreparedRuntime_FullMethodName     = "/ax.v1alpha1.AX/GetPreparedRuntime"
	AX_ReleasePreparedRuntime_FullMethodName = "/ax.v1alpha1.AX/ReleasePreparedRuntime"
	AX_PauseTask_FullMethodName              = "/ax.v1alpha1.AX/PauseTask"
	AX_CreateTaskCheckpoint_FullMethodName   = "/ax.v1alpha1.AX/CreateTaskCheckpoint"
	AX_GetTaskCheckpoint_FullMethodName      = "/ax.v1alpha1.AX/GetTaskCheckpoint"
	AX_DeleteTaskCheckpoint_FullMethodName   = "/ax.v1alpha1.AX/DeleteTaskCheckpoint"
	AX_AuthenticateRuntime_FullMethodName    = "/ax.v1alpha1.AX/AuthenticateRuntime"
	AX_GetWorkspace_FullMethodName           = "/ax.v1alpha1.AX/GetWorkspace"
	AX_ListWorkspaces_FullMethodName         = "/ax.v1alpha1.AX/ListWorkspaces"
	AX_UpdateWorkspace_FullMethodName        = "/ax.v1alpha1.AX/UpdateWorkspace"
	AX_DeleteWorkspace_FullMethodName        = "/ax.v1alpha1.AX/DeleteWorkspace"
	AX_GetModel_FullMethodName               = "/ax.v1alpha1.AX/GetModel"
	AX_ListModels_FullMethodName             = "/ax.v1alpha1.AX/ListModels"
	AX_UpdateModel_FullMethodName            = "/ax.v1alpha1.AX/UpdateModel"
	AX_DeleteModel_FullMethodName            = "/ax.v1alpha1.AX/DeleteModel"
)

// AXClient is the client API for AX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AX defines the core control plane gRPC service for autonomous agent orchestration.
type AXClient interface {
	// Tasks
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	SuspendTask(ctx context.Context, in *SuspendTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*Task, error)
	WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchTaskResponse], error)
	// Managed runtime resources. Existing ungrouped Task behavior is unchanged.
	CreateTaskGroup(ctx context.Context, in *CreateTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error)
	GetTaskGroup(ctx context.Context, in *GetTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error)
	ListTaskGroups(ctx context.Context, in *ListTaskGroupsRequest, opts ...grpc.CallOption) (*ListTaskGroupsResponse, error)
	UpdateTaskGroup(ctx context.Context, in *UpdateTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error)
	DeleteTaskGroup(ctx context.Context, in *DeleteTaskGroupRequest, opts ...grpc.CallOption) (*DeleteTaskGroupResponse, error)
	PrepareRuntime(ctx context.Context, in *PrepareRuntimeRequest, opts ...grpc.CallOption) (*PreparedRuntime, error)
	GetPreparedRuntime(ctx context.Context, in *GetPreparedRuntimeRequest, opts ...grpc.CallOption) (*PreparedRuntime, error)
	ReleasePreparedRuntime(ctx context.Context, in *ReleasePreparedRuntimeRequest, opts ...grpc.CallOption) (*ReleasePreparedRuntimeResponse, error)
	PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...grpc.CallOption) (*Task, error)
	CreateTaskCheckpoint(ctx context.Context, in *CreateTaskCheckpointRequest, opts ...grpc.CallOption) (*TaskCheckpoint, error)
	GetTaskCheckpoint(ctx context.Context, in *GetTaskCheckpointRequest, opts ...grpc.CallOption) (*TaskCheckpoint, error)
	DeleteTaskCheckpoint(ctx context.Context, in *DeleteTaskCheckpointRequest, opts ...grpc.CallOption) (*DeleteTaskCheckpointResponse, error)
	AuthenticateRuntime(ctx context.Context, in *AuthenticateRuntimeRequest, opts ...grpc.CallOption) (*AuthenticateRuntimeResponse, error)
	// Workspaces
	GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	UpdateWorkspace(ctx context.Context, in *UpdateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error)
	// Models
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*Model, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
}

type aXClient struct {
	cc grpc.ClientConnInterface
}

func NewAXClient(cc grpc.ClientConnInterface) AXClient {
	return &aXClient{cc}
}

func (c *aXClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, AX_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, AX_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, AX_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, AX_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) SuspendTask(ctx context.Context, in *SuspendTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, AX_SuspendTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, AX_ResumeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AX_ServiceDesc.Streams[0], AX_WatchTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTaskRequest, WatchTaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AX_WatchTaskClient = grpc.ServerStreamingClient[WatchTaskResponse]

func (c *aXClient) CreateTaskGroup(ctx context.Context, in *CreateTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGroup)
	err := c.cc.Invoke(ctx, AX_CreateTaskGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) GetTaskGroup(ctx context.Context, in *GetTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGroup)
	err := c.cc.Invoke(ctx, AX_GetTaskGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ListTaskGroups(ctx context.Context, in *ListTaskGroupsRequest, opts ...grpc.CallOption) (*ListTaskGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskGroupsResponse)
	err := c.cc.Invoke(ctx, AX_ListTaskGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) UpdateTaskGroup(ctx context.Context, in *UpdateTaskGroupRequest, opts ...grpc.CallOption) (*TaskGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGroup)
	err := c.cc.Invoke(ctx, AX_UpdateTaskGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) DeleteTaskGroup(ctx context.Context, in *DeleteTaskGroupRequest, opts ...grpc.CallOption) (*DeleteTaskGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskGroupResponse)
	err := c.cc.Invoke(ctx, AX_DeleteTaskGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) PrepareRuntime(ctx context.Context, in *PrepareRuntimeRequest, opts ...grpc.CallOption) (*PreparedRuntime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedRuntime)
	err := c.cc.Invoke(ctx, AX_PrepareRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) GetPreparedRuntime(ctx context.Context, in *GetPreparedRuntimeRequest, opts ...grpc.CallOption) (*PreparedRuntime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedRuntime)
	err := c.cc.Invoke(ctx, AX_GetPreparedRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ReleasePreparedRuntime(ctx context.Context, in *ReleasePreparedRuntimeRequest, opts ...grpc.CallOption) (*ReleasePreparedRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleasePreparedRuntimeResponse)
	err := c.cc.Invoke(ctx, AX_ReleasePreparedRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, AX_PauseTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) CreateTaskCheckpoint(ctx context.Context, in *CreateTaskCheckpointRequest, opts ...grpc.CallOption) (*TaskCheckpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCheckpoint)
	err := c.cc.Invoke(ctx, AX_CreateTaskCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) GetTaskCheckpoint(ctx context.Context, in *GetTaskCheckpointRequest, opts ...grpc.CallOption) (*TaskCheckpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCheckpoint)
	err := c.cc.Invoke(ctx, AX_GetTaskCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) DeleteTaskCheckpoint(ctx context.Context, in *DeleteTaskCheckpointRequest, opts ...grpc.CallOption) (*DeleteTaskCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskCheckpointResponse)
	err := c.cc.Invoke(ctx, AX_DeleteTaskCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) AuthenticateRuntime(ctx context.Context, in *AuthenticateRuntimeRequest, opts ...grpc.CallOption) (*AuthenticateRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateRuntimeResponse)
	err := c.cc.Invoke(ctx, AX_AuthenticateRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, AX_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, AX_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) UpdateWorkspace(ctx context.Context, in *UpdateWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, AX_UpdateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkspaceResponse)
	err := c.cc.Invoke(ctx, AX_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, AX_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, AX_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*Model, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Model)
	err := c.cc.Invoke(ctx, AX_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aXClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, AX_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AXServer is the server API for AX service.
// All implementations must embed UnimplementedAXServer
// for forward compatibility.
//
// AX defines the core control plane gRPC service for autonomous agent orchestration.
type AXServer interface {
	// Tasks
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	SuspendTask(context.Context, *SuspendTaskRequest) (*Task, error)
	ResumeTask(context.Context, *ResumeTaskRequest) (*Task, error)
	WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[WatchTaskResponse]) error
	// Managed runtime resources. Existing ungrouped Task behavior is unchanged.
	CreateTaskGroup(context.Context, *CreateTaskGroupRequest) (*TaskGroup, error)
	GetTaskGroup(context.Context, *GetTaskGroupRequest) (*TaskGroup, error)
	ListTaskGroups(context.Context, *ListTaskGroupsRequest) (*ListTaskGroupsResponse, error)
	UpdateTaskGroup(context.Context, *UpdateTaskGroupRequest) (*TaskGroup, error)
	DeleteTaskGroup(context.Context, *DeleteTaskGroupRequest) (*DeleteTaskGroupResponse, error)
	PrepareRuntime(context.Context, *PrepareRuntimeRequest) (*PreparedRuntime, error)
	GetPreparedRuntime(context.Context, *GetPreparedRuntimeRequest) (*PreparedRuntime, error)
	ReleasePreparedRuntime(context.Context, *ReleasePreparedRuntimeRequest) (*ReleasePreparedRuntimeResponse, error)
	PauseTask(context.Context, *PauseTaskRequest) (*Task, error)
	CreateTaskCheckpoint(context.Context, *CreateTaskCheckpointRequest) (*TaskCheckpoint, error)
	GetTaskCheckpoint(context.Context, *GetTaskCheckpointRequest) (*TaskCheckpoint, error)
	DeleteTaskCheckpoint(context.Context, *DeleteTaskCheckpointRequest) (*DeleteTaskCheckpointResponse, error)
	AuthenticateRuntime(context.Context, *AuthenticateRuntimeRequest) (*AuthenticateRuntimeResponse, error)
	// Workspaces
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	UpdateWorkspace(context.Context, *UpdateWorkspaceRequest) (*Workspace, error)
	DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error)
	// Models
	GetModel(context.Context, *GetModelRequest) (*Model, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*Model, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	mustEmbedUnimplementedAXServer()
}

// UnimplementedAXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAXServer struct{}

func (UnimplementedAXServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedAXServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAXServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedAXServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedAXServer) SuspendTask(context.Context, *SuspendTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendTask not implemented")
}
func (UnimplementedAXServer) ResumeTask(context.Context, *ResumeTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeTask not implemented")
}
func (UnimplementedAXServer) WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[WatchTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchTask not implemented")
}
func (UnimplementedAXServer) CreateTaskGroup(context.Context, *CreateTaskGroupRequest) (*TaskGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTaskGroup not implemented")
}
func (UnimplementedAXServer) GetTaskGroup(context.Context, *GetTaskGroupRequest) (*TaskGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskGroup not implemented")
}
func (UnimplementedAXServer) ListTaskGroups(context.Context, *ListTaskGroupsRequest) (*ListTaskGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskGroups not implemented")
}
func (UnimplementedAXServer) UpdateTaskGroup(context.Context, *UpdateTaskGroupRequest) (*TaskGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaskGroup not implemented")
}
func (UnimplementedAXServer) DeleteTaskGroup(context.Context, *DeleteTaskGroupRequest) (*DeleteTaskGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskGroup not implemented")
}
func (UnimplementedAXServer) PrepareRuntime(context.Context, *PrepareRuntimeRequest) (*PreparedRuntime, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareRuntime not implemented")
}
func (UnimplementedAXServer) GetPreparedRuntime(context.Context, *GetPreparedRuntimeRequest) (*PreparedRuntime, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreparedRuntime not implemented")
}
func (UnimplementedAXServer) ReleasePreparedRuntime(context.Context, *ReleasePreparedRuntimeRequest) (*ReleasePreparedRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleasePreparedRuntime not implemented")
}
func (UnimplementedAXServer) PauseTask(context.Context, *PauseTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseTask not implemented")
}
func (UnimplementedAXServer) CreateTaskCheckpoint(context.Context, *CreateTaskCheckpointRequest) (*TaskCheckpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTaskCheckpoint not implemented")
}
func (UnimplementedAXServer) GetTaskCheckpoint(context.Context, *GetTaskCheckpointRequest) (*TaskCheckpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskCheckpoint not implemented")
}
func (UnimplementedAXServer) DeleteTaskCheckpoint(context.Context, *DeleteTaskCheckpointRequest) (*DeleteTaskCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskCheckpoint not implemented")
}
func (UnimplementedAXServer) AuthenticateRuntime(context.Context, *AuthenticateRuntimeRequest) (*AuthenticateRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateRuntime not implemented")
}
func (UnimplementedAXServer) GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedAXServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedAXServer) UpdateWorkspace(context.Context, *UpdateWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkspace not implemented")
}
func (UnimplementedAXServer) DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedAXServer) GetModel(context.Context, *GetModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedAXServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAXServer) UpdateModel(context.Context, *UpdateModelRequest) (*Model, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedAXServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedAXServer) mustEmbedUnimplementedAXServer() {}
func (UnimplementedAXServer) testEmbeddedByValue()            {}

// UnsafeAXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AXServer will
// result in compilation errors.
type UnsafeAXServer interface {
	mustEmbedUnimplementedAXServer()
}

func RegisterAXServer(s grpc.ServiceRegistrar, srv AXServer) {
	// If the following call panics, it indicates UnimplementedAXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AX_ServiceDesc, srv)
}

func _AX_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_SuspendTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).SuspendTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_SuspendTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).SuspendTask(ctx, req.(*SuspendTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ResumeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ResumeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ResumeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ResumeTask(ctx, req.(*ResumeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_WatchTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AXServer).WatchTask(m, &grpc.GenericServerStream[WatchTaskRequest, WatchTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AX_WatchTaskServer = grpc.ServerStreamingServer[WatchTaskResponse]

func _AX_CreateTaskGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).CreateTaskGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_CreateTaskGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).CreateTaskGroup(ctx, req.(*CreateTaskGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_GetTaskGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetTaskGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetTaskGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetTaskGroup(ctx, req.(*GetTaskGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ListTaskGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ListTaskGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ListTaskGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ListTaskGroups(ctx, req.(*ListTaskGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_UpdateTaskGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).UpdateTaskGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_UpdateTaskGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).UpdateTaskGroup(ctx, req.(*UpdateTaskGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_DeleteTaskGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).DeleteTaskGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_DeleteTaskGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).DeleteTaskGroup(ctx, req.(*DeleteTaskGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_PrepareRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).PrepareRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_PrepareRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).PrepareRuntime(ctx, req.(*PrepareRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_GetPreparedRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreparedRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetPreparedRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetPreparedRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetPreparedRuntime(ctx, req.(*GetPreparedRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ReleasePreparedRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePreparedRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ReleasePreparedRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ReleasePreparedRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ReleasePreparedRuntime(ctx, req.(*ReleasePreparedRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_PauseTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).PauseTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_PauseTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).PauseTask(ctx, req.(*PauseTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_CreateTaskCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).CreateTaskCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_CreateTaskCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).CreateTaskCheckpoint(ctx, req.(*CreateTaskCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_GetTaskCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetTaskCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetTaskCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetTaskCheckpoint(ctx, req.(*GetTaskCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_DeleteTaskCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).DeleteTaskCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_DeleteTaskCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).DeleteTaskCheckpoint(ctx, req.(*DeleteTaskCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_AuthenticateRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).AuthenticateRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_AuthenticateRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).AuthenticateRuntime(ctx, req.(*AuthenticateRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetWorkspace(ctx, req.(*GetWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_UpdateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).UpdateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_UpdateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).UpdateWorkspace(ctx, req.(*UpdateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).DeleteWorkspace(ctx, req.(*DeleteWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AX_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AXServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AX_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AXServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AX_ServiceDesc is the grpc.ServiceDesc for AX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ax.v1alpha1.AX",
	HandlerType: (*AXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _AX_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AX_ListTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _AX_CreateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _AX_DeleteTask_Handler,
		},
		{
			MethodName: "SuspendTask",
			Handler:    _AX_SuspendTask_Handler,
		},
		{
			MethodName: "ResumeTask",
			Handler:    _AX_ResumeTask_Handler,
		},
		{
			MethodName: "CreateTaskGroup",
			Handler:    _AX_CreateTaskGroup_Handler,
		},
		{
			MethodName: "GetTaskGroup",
			Handler:    _AX_GetTaskGroup_Handler,
		},
		{
			MethodName: "ListTaskGroups",
			Handler:    _AX_ListTaskGroups_Handler,
		},
		{
			MethodName: "UpdateTaskGroup",
			Handler:    _AX_UpdateTaskGroup_Handler,
		},
		{
			MethodName: "DeleteTaskGroup",
			Handler:    _AX_DeleteTaskGroup_Handler,
		},
		{
			MethodName: "PrepareRuntime",
			Handler:    _AX_PrepareRuntime_Handler,
		},
		{
			MethodName: "GetPreparedRuntime",
			Handler:    _AX_GetPreparedRuntime_Handler,
		},
		{
			MethodName: "ReleasePreparedRuntime",
			Handler:    _AX_ReleasePreparedRuntime_Handler,
		},
		{
			MethodName: "PauseTask",
			Handler:    _AX_PauseTask_Handler,
		},
		{
			MethodName: "CreateTaskCheckpoint",
			Handler:    _AX_CreateTaskCheckpoint_Handler,
		},
		{
			MethodName: "GetTaskCheckpoint",
			Handler:    _AX_GetTaskCheckpoint_Handler,
		},
		{
			MethodName: "DeleteTaskCheckpoint",
			Handler:    _AX_DeleteTaskCheckpoint_Handler,
		},
		{
			MethodName: "AuthenticateRuntime",
			Handler:    _AX_AuthenticateRuntime_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _AX_GetWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _AX_ListWorkspaces_Handler,
		},
		{
			MethodName: "UpdateWorkspace",
			Handler:    _AX_UpdateWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _AX_DeleteWorkspace_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _AX_GetModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AX_ListModels_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _AX_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _AX_DeleteModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTask",
			Handler:       _AX_WatchTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ax.proto",
}
