// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: execution.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExecutionService_StartProcess_FullMethodName         = "/ax.v1alpha1.TaskExecutionService/StartProcess"
	TaskExecutionService_GetProcess_FullMethodName           = "/ax.v1alpha1.TaskExecutionService/GetProcess"
	TaskExecutionService_KillProcess_FullMethodName          = "/ax.v1alpha1.TaskExecutionService/KillProcess"
	TaskExecutionService_StreamProcessOutputs_FullMethodName = "/ax.v1alpha1.TaskExecutionService/StreamProcessOutputs"
	TaskExecutionService_ReadFile_FullMethodName             = "/ax.v1alpha1.TaskExecutionService/ReadFile"
	TaskExecutionService_WriteFile_FullMethodName            = "/ax.v1alpha1.TaskExecutionService/WriteFile"
)

// TaskExecutionServiceClient is the client API for TaskExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stable AX execution API. Guest protocol translation is private to AX.
type TaskExecutionServiceClient interface {
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error)
	GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*Process, error)
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error)
	StreamProcessOutputs(ctx context.Context, in *StreamProcessOutputsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error)
}

type taskExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutionServiceClient(cc grpc.ClientConnInterface) TaskExecutionServiceClient {
	return &taskExecutionServiceClient{cc}
}

func (c *taskExecutionServiceClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProcessResponse)
	err := c.cc.Invoke(ctx, TaskExecutionService_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutionServiceClient) GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, TaskExecutionService_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutionServiceClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillProcessResponse)
	err := c.cc.Invoke(ctx, TaskExecutionService_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutionServiceClient) StreamProcessOutputs(ctx context.Context, in *StreamProcessOutputsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecutionService_ServiceDesc.Streams[0], TaskExecutionService_StreamProcessOutputs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProcessOutputsRequest, OutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_StreamProcessOutputsClient = grpc.ServerStreamingClient[OutputChunk]

func (c *taskExecutionServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecutionService_ServiceDesc.Streams[1], TaskExecutionService_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_ReadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *taskExecutionServiceClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecutionService_ServiceDesc.Streams[2], TaskExecutionService_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileRequest, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_WriteFileClient = grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse]

// TaskExecutionServiceServer is the server API for TaskExecutionService service.
// All implementations must embed UnimplementedTaskExecutionServiceServer
// for forward compatibility.
//
// Stable AX execution API. Guest protocol translation is private to AX.
type TaskExecutionServiceServer interface {
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error)
	GetProcess(context.Context, *GetProcessRequest) (*Process, error)
	KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error)
	StreamProcessOutputs(*StreamProcessOutputsRequest, grpc.ServerStreamingServer[OutputChunk]) error
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error
	mustEmbedUnimplementedTaskExecutionServiceServer()
}

// UnimplementedTaskExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutionServiceServer struct{}

func (UnimplementedTaskExecutionServiceServer) StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedTaskExecutionServiceServer) GetProcess(context.Context, *GetProcessRequest) (*Process, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedTaskExecutionServiceServer) KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedTaskExecutionServiceServer) StreamProcessOutputs(*StreamProcessOutputsRequest, grpc.ServerStreamingServer[OutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessOutputs not implemented")
}
func (UnimplementedTaskExecutionServiceServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedTaskExecutionServiceServer) WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedTaskExecutionServiceServer) mustEmbedUnimplementedTaskExecutionServiceServer() {}
func (UnimplementedTaskExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTaskExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutionServiceServer will
// result in compilation errors.
type UnsafeTaskExecutionServiceServer interface {
	mustEmbedUnimplementedTaskExecutionServiceServer()
}

func RegisterTaskExecutionServiceServer(s grpc.ServiceRegistrar, srv TaskExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecutionService_ServiceDesc, srv)
}

func _TaskExecutionService_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutionServiceServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutionService_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutionServiceServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutionService_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutionServiceServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutionService_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutionServiceServer).GetProcess(ctx, req.(*GetProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutionService_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutionServiceServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutionService_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutionServiceServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutionService_StreamProcessOutputs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProcessOutputsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskExecutionServiceServer).StreamProcessOutputs(m, &grpc.GenericServerStream[StreamProcessOutputsRequest, OutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_StreamProcessOutputsServer = grpc.ServerStreamingServer[OutputChunk]

func _TaskExecutionService_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskExecutionServiceServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_ReadFileServer = grpc.ServerStreamingServer[FileChunk]

func _TaskExecutionService_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskExecutionServiceServer).WriteFile(&grpc.GenericServerStream[WriteFileRequest, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutionService_WriteFileServer = grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]

// TaskExecutionService_ServiceDesc is the grpc.ServiceDesc for TaskExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ax.v1alpha1.TaskExecutionService",
	HandlerType: (*TaskExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcess",
			Handler:    _TaskExecutionService_StartProcess_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _TaskExecutionService_GetProcess_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _TaskExecutionService_KillProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessOutputs",
			Handler:       _TaskExecutionService_StreamProcessOutputs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadFile",
			Handler:       _TaskExecutionService_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _TaskExecutionService_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "execution.proto",
}
