// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: execution.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_UNSPECIFIED ProcessStatus = 0
	ProcessStatus_PROCESS_STATUS_RUNNING     ProcessStatus = 1
	ProcessStatus_PROCESS_STATUS_COMPLETED   ProcessStatus = 2
	ProcessStatus_PROCESS_STATUS_FAILED      ProcessStatus = 3
	ProcessStatus_PROCESS_STATUS_TERMINATED  ProcessStatus = 4
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_UNSPECIFIED",
		1: "PROCESS_STATUS_RUNNING",
		2: "PROCESS_STATUS_COMPLETED",
		3: "PROCESS_STATUS_FAILED",
		4: "PROCESS_STATUS_TERMINATED",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_UNSPECIFIED": 0,
		"PROCESS_STATUS_RUNNING":     1,
		"PROCESS_STATUS_COMPLETED":   2,
		"PROCESS_STATUS_FAILED":      3,
		"PROCESS_STATUS_TERMINATED":  4,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

type OutputSource int32

const (
	OutputSource_OUTPUT_SOURCE_UNSPECIFIED OutputSource = 0
	OutputSource_OUTPUT_SOURCE_STDOUT      OutputSource = 1
	OutputSource_OUTPUT_SOURCE_STDERR      OutputSource = 2
)

// Enum value maps for OutputSource.
var (
	OutputSource_name = map[int32]string{
		0: "OUTPUT_SOURCE_UNSPECIFIED",
		1: "OUTPUT_SOURCE_STDOUT",
		2: "OUTPUT_SOURCE_STDERR",
	}
	OutputSource_value = map[string]int32{
		"OUTPUT_SOURCE_UNSPECIFIED": 0,
		"OUTPUT_SOURCE_STDOUT":      1,
		"OUTPUT_SOURCE_STDERR":      2,
	}
)

func (x OutputSource) Enum() *OutputSource {
	p := new(OutputSource)
	*p = x
	return p
}

func (x OutputSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputSource) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_proto_enumTypes[1].Descriptor()
}

func (OutputSource) Type() protoreflect.EnumType {
	return &file_execution_proto_enumTypes[1]
}

func (x OutputSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputSource.Descriptor instead.
func (OutputSource) EnumDescriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Status        ProcessStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ax.v1alpha1.ProcessStatus" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Command       []string               `protobuf:"bytes,6,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Process) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_STATUS_UNSPECIFIED
}

func (x *Process) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Process) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Process) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Process) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *StartProcessRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *StartProcessRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartProcessRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartProcessRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartProcessRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *StartProcessResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type GetProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcessRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *GetProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Kills the process group with SIGKILL, including child processes.
type KillProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *KillProcessRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *KillProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type KillProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *KillProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StreamProcessOutputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	ProcessId     string                 `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	StdoutOffset  int64                  `protobuf:"varint,3,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	StderrOffset  int64                  `protobuf:"varint,4,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessOutputsRequest) Reset() {
	*x = StreamProcessOutputsRequest{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessOutputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessOutputsRequest) ProtoMessage() {}

func (x *StreamProcessOutputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessOutputsRequest.ProtoReflect.Descriptor instead.
func (*StreamProcessOutputsRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *StreamProcessOutputsRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *StreamProcessOutputsRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StreamProcessOutputsRequest) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *StreamProcessOutputsRequest) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

func (x *StreamProcessOutputsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        OutputSource           `protobuf:"varint,1,opt,name=source,proto3,enum=ax.v1alpha1.OutputSource" json:"source,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	NextOffset    int64                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	Exit          *Process               `protobuf:"bytes,4,opt,name=exit,proto3" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{7}
}

func (x *OutputChunk) GetSource() OutputSource {
	if x != nil {
		return x.Source
	}
	return OutputSource_OUTPUT_SOURCE_UNSPECIFIED
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OutputChunk) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *OutputChunk) GetExit() *Process {
	if x != nil {
		return x.Exit
	}
	return nil
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskRef       *ResourceRef           `protobuf:"bytes,1,opt,name=task_ref,json=taskRef,proto3" json:"task_ref,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetTaskRef() *ResourceRef {
	if x != nil {
		return x.TaskRef
	}
	return nil
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\vax.v1alpha1\x1a\bax.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\aProcess\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.ax.v1alpha1.ProcessStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x18\n" +
	"\acommand\x18\x06 \x03(\tR\acommand\"\x8a\x02\n" +
	"\x13StartProcessRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12;\n" +
	"\x03env\x18\x04 \x03(\v2).ax.v1alpha1.StartProcessRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14StartProcessResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"g\n" +
	"\x11GetProcessRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\"h\n" +
	"\x12KillProcessRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\"2\n" +
	"\x13KillProcessResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\xd3\x01\n" +
	"\x1bStreamProcessOutputsRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12#\n" +
	"\rstdout_offset\x18\x03 \x01(\x03R\fstdoutOffset\x12#\n" +
	"\rstderr_offset\x18\x04 \x01(\x03R\fstderrOffset\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"\x9f\x01\n" +
	"\vOutputChunk\x121\n" +
	"\x06source\x18\x01 \x01(\x0e2\x19.ax.v1alpha1.OutputSourceR\x06source\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x03R\n" +
	"nextOffset\x12(\n" +
	"\x04exit\x18\x04 \x01(\v2\x14.ax.v1alpha1.ProcessR\x04exit\"Z\n" +
	"\x0fReadFileRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x85\x01\n" +
	"\x10WriteFileRequest\x123\n" +
	"\btask_ref\x18\x01 \x01(\v2\x18.ax.v1alpha1.ResourceRefR\ataskRef\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten*\xa3\x01\n" +
	"\rProcessStatus\x12\x1e\n" +
	"\x1aPROCESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18PROCESS_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PROCESS_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19PROCESS_STATUS_TERMINATED\x10\x04*a\n" +
	"\fOutputSource\x12\x1d\n" +
	"\x19OUTPUT_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OUTPUT_SOURCE_STDOUT\x10\x01\x12\x18\n" +
	"\x14OUTPUT_SOURCE_STDERR\x10\x022\xf1\x03\n" +
	"\x14TaskExecutionService\x12S\n" +
	"\fStartProcess\x12 .ax.v1alpha1.StartProcessRequest\x1a!.ax.v1alpha1.StartProcessResponse\x12B\n" +
	"\n" +
	"GetProcess\x12\x1e.ax.v1alpha1.GetProcessRequest\x1a\x14.ax.v1alpha1.Process\x12P\n" +
	"\vKillProcess\x12\x1f.ax.v1alpha1.KillProcessRequest\x1a .ax.v1alpha1.KillProcessResponse\x12\\\n" +
	"\x14StreamProcessOutputs\x12(.ax.v1alpha1.StreamProcessOutputsRequest\x1a\x18.ax.v1alpha1.OutputChunk0\x01\x12B\n" +
	"\bReadFile\x12\x1c.ax.v1alpha1.ReadFileRequest\x1a\x16.ax.v1alpha1.FileChunk0\x01\x12L\n" +
	"\tWriteFile\x12\x1d.ax.v1alpha1.WriteFileRequest\x1a\x1e.ax.v1alpha1.WriteFileResponse(\x01B(Z&github.com/google/ax/pkg/apis/v1alpha1b\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_execution_proto_goTypes = []any{
	(ProcessStatus)(0),                  // 0: ax.v1alpha1.ProcessStatus
	(OutputSource)(0),                   // 1: ax.v1alpha1.OutputSource
	(*Process)(nil),                     // 2: ax.v1alpha1.Process
	(*StartProcessRequest)(nil),         // 3: ax.v1alpha1.StartProcessRequest
	(*StartProcessResponse)(nil),        // 4: ax.v1alpha1.StartProcessResponse
	(*GetProcessRequest)(nil),           // 5: ax.v1alpha1.GetProcessRequest
	(*KillProcessRequest)(nil),          // 6: ax.v1alpha1.KillProcessRequest
	(*KillProcessResponse)(nil),         // 7: ax.v1alpha1.KillProcessResponse
	(*StreamProcessOutputsRequest)(nil), // 8: ax.v1alpha1.StreamProcessOutputsRequest
	(*OutputChunk)(nil),                 // 9: ax.v1alpha1.OutputChunk
	(*ReadFileRequest)(nil),             // 10: ax.v1alpha1.ReadFileRequest
	(*FileChunk)(nil),                   // 11: ax.v1alpha1.FileChunk
	(*WriteFileRequest)(nil),            // 12: ax.v1alpha1.WriteFileRequest
	(*WriteFileResponse)(nil),           // 13: ax.v1alpha1.WriteFileResponse
	nil,                                 // 14: ax.v1alpha1.StartProcessRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*ResourceRef)(nil),                 // 16: ax.v1alpha1.ResourceRef
}
var file_execution_proto_depIdxs = []int32{
	0,  // 0: ax.v1alpha1.Process.status:type_name -> ax.v1alpha1.ProcessStatus
	15, // 1: ax.v1alpha1.Process.started_at:type_name -> google.protobuf.Timestamp
	15, // 2: ax.v1alpha1.Process.finished_at:type_name -> google.protobuf.Timestamp
	16, // 3: ax.v1alpha1.StartProcessRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	14, // 4: ax.v1alpha1.StartProcessRequest.env:type_name -> ax.v1alpha1.StartProcessRequest.EnvEntry
	16, // 5: ax.v1alpha1.GetProcessRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	16, // 6: ax.v1alpha1.KillProcessRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	16, // 7: ax.v1alpha1.StreamProcessOutputsRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	1,  // 8: ax.v1alpha1.OutputChunk.source:type_name -> ax.v1alpha1.OutputSource
	2,  // 9: ax.v1alpha1.OutputChunk.exit:type_name -> ax.v1alpha1.Process
	16, // 10: ax.v1alpha1.ReadFileRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	16, // 11: ax.v1alpha1.WriteFileRequest.task_ref:type_name -> ax.v1alpha1.ResourceRef
	3,  // 12: ax.v1alpha1.TaskExecutionService.StartProcess:input_type -> ax.v1alpha1.StartProcessRequest
	5,  // 13: ax.v1alpha1.TaskExecutionService.GetProcess:input_type -> ax.v1alpha1.GetProcessRequest
	6,  // 14: ax.v1alpha1.TaskExecutionService.KillProcess:input_type -> ax.v1alpha1.KillProcessRequest
	8,  // 15: ax.v1alpha1.TaskExecutionService.StreamProcessOutputs:input_type -> ax.v1alpha1.StreamProcessOutputsRequest
	10, // 16: ax.v1alpha1.TaskExecutionService.ReadFile:input_type -> ax.v1alpha1.ReadFileRequest
	12, // 17: ax.v1alpha1.TaskExecutionService.WriteFile:input_type -> ax.v1alpha1.WriteFileRequest
	4,  // 18: ax.v1alpha1.TaskExecutionService.StartProcess:output_type -> ax.v1alpha1.StartProcessResponse
	2,  // 19: ax.v1alpha1.TaskExecutionService.GetProcess:output_type -> ax.v1alpha1.Process
	7,  // 20: ax.v1alpha1.TaskExecutionService.KillProcess:output_type -> ax.v1alpha1.KillProcessResponse
	9,  // 21: ax.v1alpha1.TaskExecutionService.StreamProcessOutputs:output_type -> ax.v1alpha1.OutputChunk
	11, // 22: ax.v1alpha1.TaskExecutionService.ReadFile:output_type -> ax.v1alpha1.FileChunk
	13, // 23: ax.v1alpha1.TaskExecutionService.WriteFile:output_type -> ax.v1alpha1.WriteFileResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	file_ax_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		EnumInfos:         file_execution_proto_enumTypes,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
